[package]
name = "data_structures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.56"

[dev-dependencies]
anyhow = "1.0.79"
debug_print = "1.0.0"
